const capabilities = [
  { group: 'search', route: '/search', methods: ['GET', 'POST'], auth: false, app_context: false, raw: true, description: 'PC 搜索歌曲' },
  { group: 'search', route: '/search/playlist', methods: ['GET', 'POST'], auth: false, app_context: false, raw: true, description: 'PC 搜索歌单或从混合搜索提取歌单' },
  { group: 'search', route: '/search/mixed', methods: ['GET', 'POST'], auth: false, app_context: false, raw: true, description: 'PC 混合搜索' },
  { group: 'playlist', route: '/recommend/playlist', methods: ['GET', 'POST'], auth: false, app_context: false, raw: true, description: '推荐歌单' },
  { group: 'playlist', route: '/playlist/detail', methods: ['GET', 'POST'], auth: false, app_context: false, raw: true, description: '歌单详情与媒体资源' },
  { group: 'playlist', route: '/playlist/related/media', methods: ['GET', 'POST'], auth: true, app_context: true, raw: true, description: '歌单相关推荐媒体' },
  { group: 'playlist', route: '/playlist/feed/media', methods: ['GET', 'POST'], auth: true, app_context: true, raw: true, description: '歌单 Feed 媒体流' },
  { group: 'feed', route: '/discover', methods: ['GET', 'POST'], auth: false, app_context: false, raw: true, description: '发现页块' },
  { group: 'feed', route: '/discover/mix', methods: ['GET', 'POST'], auth: false, app_context: false, raw: true, description: '发现页混合推荐流' },
  { group: 'feed', route: '/feed/mode', methods: ['GET', 'POST'], auth: false, app_context: false, raw: true, description: 'Feed 模式数据' },
  { group: 'feed', route: '/feed/mode/guidance', methods: ['GET', 'POST'], auth: false, app_context: false, raw: true, description: 'Feed 模式引导' },
  { group: 'feed', route: '/daily/mix', methods: ['GET', 'POST'], auth: true, app_context: true, raw: true, description: 'Daily Mix 推荐歌曲流' },
  { group: 'feed', route: '/radio/list', methods: ['GET', 'POST'], auth: false, app_context: false, raw: true, description: '电台列表' },
  { group: 'feed', route: '/radio/tracks', methods: ['GET', 'POST'], auth: false, app_context: false, raw: true, description: '电台歌曲 Feed' },
  { group: 'feed', route: '/feed/listen/video', methods: ['GET', 'POST'], auth: true, app_context: true, raw: true, description: '听视频 Feed' },
  { group: 'media', route: '/track/detail', methods: ['GET', 'POST'], auth: false, app_context: false, raw: true, description: 'PC 曲目详情' },
  { group: 'media', route: '/video/detail', methods: ['POST'], auth: true, app_context: false, raw: true, description: 'PC 视频详情' },
  { group: 'media', route: '/h5/seo/track', methods: ['GET', 'POST'], auth: false, app_context: false, raw: true, description: 'H5 SEO 曲目详情' },
  { group: 'media', route: '/media/player', methods: ['GET', 'POST'], auth: true, app_context: true, raw: false, description: 'App 播放信息摘要' },
  { group: 'comment', route: '/comment', methods: ['GET', 'POST'], auth: false, app_context: false, raw: true, description: '歌曲评论列表' },
  { group: 'auth', route: '/auth/qrcode', methods: ['GET'], auth: false, app_context: false, raw: true, description: '获取扫码登录二维码' },
  { group: 'auth', route: '/auth/qrcode/status', methods: ['POST'], auth: false, app_context: false, raw: true, description: '轮询扫码登录状态' },
  { group: 'auth', route: '/auth/me', methods: ['POST'], auth: true, app_context: false, raw: true, description: '账号信息' },
  { group: 'auth', route: '/me/playlists', methods: ['POST'], auth: true, app_context: false, raw: true, description: '我的歌单' },
  { group: 'auth', route: '/me/collection/mixed', methods: ['POST'], auth: true, app_context: false, raw: true, description: '我的收藏混合资源' },
  { group: 'share', route: '/song/detail', methods: ['GET', 'POST'], auth: false, app_context: false, raw: true, description: '歌曲详情或分享页解析' },
  { group: 'share', route: '/lyric', methods: ['GET', 'POST'], auth: false, app_context: false, raw: true, description: '歌词解析' },
  { group: 'share', route: '/share/resolve', methods: ['GET', 'POST'], auth: false, app_context: false, raw: true, description: '分享链接资源识别' },
  { group: 'audio', route: '/audio/info', methods: ['GET', 'POST'], auth: false, app_context: false, raw: true, description: '音频信息摘要' },
  { group: 'audio', route: '/download/url', methods: ['GET', 'POST'], auth: false, app_context: false, raw: true, description: '解析曲目音频地址' },
  { group: 'audio', route: '/download/file', methods: ['POST'], auth: false, app_context: false, raw: false, description: '受控下载音频文件' },
  { group: 'audio', route: '/decrypt/spade', methods: ['POST'], auth: false, app_context: false, raw: false, description: '解密受控音频令牌' },
  { group: 'audio', route: '/audio/decrypt', methods: ['POST'], auth: false, app_context: false, raw: false, description: '本地解密加密音频' },
  { group: 'system', route: '/api/capabilities', methods: ['GET'], auth: false, app_context: false, raw: false, description: '能力矩阵' },
]

module.exports = { capabilities }
